/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uts;

/**
 *
 * @author mkhai
 */
public class ResepMakanan extends javax.swing.JFrame {

    /**
     * Creates new form ResepMakanan
     */
    public ResepMakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBahan = new javax.swing.JTextArea();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resep Makanan"));

        jLabel1.setText("Nasi Goreng");

        jLabel2.setText("Mie Goreng");

        jLabel3.setText("Bakso");

        button1.setBackground(new java.awt.Color(255, 255, 204));
        button1.setText("Pilih");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 255, 204));
        button2.setText("Pilih");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 255, 204));
        button3.setText("Pilih");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Soto Lamongan");

        jLabel5.setText("Sop Buntut");

        jLabel6.setText("Nasi Padang");

        button4.setBackground(new java.awt.Color(255, 255, 204));
        button4.setText("Pilih");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(255, 255, 204));
        button5.setText("Pilih");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(255, 255, 204));
        button6.setText("Pilih");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Bahan yang diperlukan :");

        textBahan.setColumns(20);
        textBahan.setRows(5);
        jScrollPane1.setViewportView(textBahan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(button1)))
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(button6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(button4)))))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(button1)
                    .addComponent(jLabel4)
                    .addComponent(button4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(button2)
                    .addComponent(jLabel5)
                    .addComponent(button5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(button3)
                    .addComponent(jLabel6)
                    .addComponent(button6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonHapus.setBackground(new java.awt.Color(255, 204, 204));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKeluar.setBackground(new java.awt.Color(255, 204, 204));
        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(buttonHapus)
                .addGap(18, 18, 18)
                .addComponent(buttonKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonKeluar)
                    .addComponent(buttonHapus))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        textBahan.setText("");        
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        textBahan.setText("""
                          Bahannya :
                          - 1 siung bawang putih, cincang
                          - 2 buah cabai rawit, cincang
                          - Garam dan gula secukupnya
                          - 1 piring nasi putih
                          - 4 siung bawang merah, cincang
                          - 1 batang daun seledri, cincang
                          - 1 butir telur, kocok lepas
                          - 1 genggam kol, potong-potong dan goreng
                          - 1 sdm saus tiram
                          
                          Cara membuatnya :
                          1. Tumis bawang putih dan bawang merah. Masukkan cabai lalu tumis lagi sebentar.                          
                          2. Masukkan telur dan goreng orak arik hingga matang.                          
                          3. Masukkan nasi dan kol goreng, aduk rata. Masukkan saus tiram dan daun seledri. Aduk rata.                          
                          4. Tambahkan gula dan garam secukupnya.                          
                          5. Aduk rata.""");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        textBahan.setText("""
                          Bahannya :
                          - Mi basah atau mie telor 500 g
                          - Daging ayam 300 g                          
                          - Minyak ayam 500 ml                          
                          - Bawang putih 4 siung                          
                          - Bawang merah 4 buah                          
                          - Ketumbar 1 sdt                          
                          - Kunyit seruas jari                          
                          - Kemiri 4 butir                          
                          - Jahe 1 ruas                          
                          - Air rebusan daging ayam 2 L                          
                          - Lada bubuk 1 sdt                          
                          - Garam 1 sdt                          
                          - Tulang ayam secukupnya
                          
                          Cara membuatnya : 
                          1. Buat kuah kaldu mi ayam terlebih dahulu, yaitu dengan merebus lagi air rebusan daging ayam ditambahkan dengan lada bubuk, garam, dan tulang ayam secukupnya.                          
                          2. Buat toping ayam.                          
                          3. Ayam yang telah direbus kemudian di potong kecil-kecil atau potong halus.                          
                          4. Haluskan bumbu yang terdiri dari bawang putih, bawang merah, ketumbar, kunyit, kemiri, dan jahe.                          
                          5. Tumis ayam dengan bumbu yang telah dihaluskan.                          
                          6. Tambahkan garam dan penyedap rasa secukupnya.                          
                          7. Setelah kuah mi ayam dan toping ayam siap, rebus mie yang sudah disiapkan.                          
                          8. Saat merebus mi, siapkan mangkuk.                          
                          9. Kemudian tambahkan 1 sdm minyak ayam dan 1 sdt merica.                          
                          10. Masukkan mi yang telah matang ke dalam mangkuk.                          
                          11. Kemudian aduk mi hingga tercampur sempurna dengan minyak ayam.                         
                          12. Tambahkan toping ayam dan kuah ayam.                          
                          13. Mi ayam siap disantap.
                          """);
    }//GEN-LAST:event_button2ActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        textBahan.setText("""
                          Bahannya:
                          - 500 gram daging sapi tanpa lemak                          
                          - 150 gram es batu                          
                          - 1 sdm bawang putih gurih, haluskan                          
                          - 1 sdm bawang merah goreng, haluskan                          
                          - 1 sdt gula pasir                          
                          - 2 sdt garam                          
                          - 1 butir putih telur                          
                          - 1/2 sdt lada bubuk                          
                          - 100 gram tepung sagu                          
                          - 1/2 sdt baking powder
                          
                          Cara membuatnya :
                          1. Cuci bersih daging lalu potong kecil-kecil. Setelah itu masukkan di blender atau food processor dan haluskan.                          
                          2. Masukkan separuh es batu, bawang putih, dan bawang merah. Giling lagi sampai halus. Tambahkan garam. Giling kembali.                          
                          3. Tambahkan gula pasir, lada bubuk, putih telur, tapung sagu, dan baking powder. Tambahkan lagi sisa es batu. Giling sampai halus.                          
                          4. Pastikan adonan daging selalu dalam keadaan dingin (dengan memasukkan es batu secara bertahap). Giling sampai adonan bakso halus dan berwarna sedikit merah muda.                          
                          5. Didihkan air. Setelah air mendidih, kecilkan api. Pastikan air untuk merebus daging tidak dalam keadaan "bergejolak". Bentuk adonan bakso bulat-bulat, lalu masukkan ke dalam air rebusan. Lakukan sampai adonan habis.                          
                          6. Untuk menghasilkan bakso daging sapi yang matangnya sempurna dan merata, setelah bakso mengambang, besarkan apinya sedikit. Masak kembali selama kurang lebih 5 menit.                          
                          7. Siapkan wadah yang berisi air matang dingin (bisa ditambah es batu). Bakso yang sudah matang segera dipindahkan ke dalam air dingin. Tujuannya agar teksturnya lebih kenyal. Setelah itu tiriskan.
                          """);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        textBahan.setText("""
                          Bahannya:
                          - 1 ekor (1 kg) ayam kampung
                          - 2 liter air
                          - 3 sdm minyak sayur
                          - 2 batang daun bawang, potong kasar
                          - 2 batang serai, memarkan
                          - 3 lembar daun jeruk purut
                          - 3 lembar daun salam
                          - 3 cm lengkuas, memarkan
                          Haluskan:
                          - 5 siung bawang putih
                          - 3 butir bawang merah
                          - 4 butir kemiri
                          - 4 cm kunyit tua,bakar,kerok
                          - 1 cm jahe
                          - 1 sdt merica butiran
                          - 2 sdt gula pasir
                          - 2 sdt garam
                          Koya Udang:
                          - 5 buah kerupuk udang
                          - 1 sdm bawang putih goreng
                          Isian:
                          - 25 g suun, rendam hingga lunak, tiriskan
                          - 2 buah tomat, iris kasar
                          - 50 g kol, iris kasar
                          - 2 butir telur rebus
                          Pelengkap
                          - daun bawang iris halus
                          - bawang merah goreng
                          - sambal rawit merah
                          - kecap manis
                          - jeruk nipis
                          
                          Cara membuatnya : 
                          1. Potong ayam menjadi 4 bagian lalu cuci bersih dan tiriskan.
                          2. Didihkan air dalam panci, masukkan ayam, kecilkan api. Masak hingga daging ayam hampir lunak.
                          3. Tumis Bumbu Halus hingga wangi.
                          4. Tambahkan serai, daun jeruk, daun salam dan lengkuas. Aduk hingga harum, angkat, masukkan ke dalam rebusan ayam. Tambahkan air hingga kaldunya 2 liter.
                          5. Masukkan daun bawang, kecilkan api. Masak terus hingga ayam lunak. Matikan api.
                          6. Angkat potongan ayam dan tiriskan.
                          Koya Udang:
                          7. Masukkan kerupuk udang dan bawang putih goreng dalam grinder, proses hingga halus.
                          Penyajian:
                          8. Taruh suun, kol, tomat dan suwiran ayam dalam mangkuk.
                          9. Tuangi kaldu panas. Taburi koya udang.
                          10. Sajikan dengan Pelengkapnya.                                                    
                          """);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        textBahan.setText("""
                          Bahannya :
                          - 1½ kg buntut sapi
                          - 12 siung bawang putih
                          - 1½ sdm merica putih utuh
                          - 5 iris pala
                          - 7-8 biji cengkeh
                          - 8 siung bawang merah rajang
                          - 8 siung bawang putih rajang
                          - 2-3 tangkai seledri
                          - 3-4 tangkai daun bawang
                          - 3 buah tomat belah
                          - 4 3/4 sdt gula pasir
                          - Kentang yang sudah dikupas, dipotong dadu, dan direbus
                          - Wortel yang sudah dikupas, diiris, dan direbus
                          
                          Cara membuatnya :
                          1. Langkah pertama untuk membuat sop buntut adalah didihkan air lalu masukkan buntut sapi, rebus hingga setengah mendidih, kemudian angkat dan tiriskan. Tips untuk  mendapatkan kuah sop buntut yang jernih, sebaiknya buntut mentah tidak dicuci. Baca juga: Jangan Buang Pisang Hampir Busuk, Coba Resep Bolu Kukus Pisang
                          2. Setelah setengah direbus baru cuci dan bersihkan buntut sapi dengan air dingin mengalir. Setelah dicuci bersih, tambahkan air dingin secukupnya untuk merebus buntut sapi dengan api kecil. Rebus sampai mendidih kembali.
                          3. Sembari menunggu, kamu bisa haluskan bawang putih bersama merica, setelah halus dilanjutkan dengan menumis dengan minyak secukupnya. Jika warna bumbu sudah agak cokelat muda, tuangkan dua gelas air lalu didihkan hingga mendidih. Kemudian tuang dengan disaring ke dalam kuah buntut yang sudah mendidih. Langkah ini bisa disesuaikan dengan selera, jika ingin tidak disaring tidak masalah. Baca juga: Resep Praktis Chicken Piccata Milenesse, Ide Menu Makan Malam
                          4. Tambahkan irisan pala, cengkeh dan daun bawang serta seledri yang sudah disimpulkan. Sebaiknya seledri dimasukkan utuh dan tidak diiris tipis-tipis. Lalu tambahkan garam dan penyedap. Angkat seledri yang sudah layu, buang dan rebus buntut sapi sampai empuk. Baca juga: Resep Seared Rib Eye with Mushroom Sauce, Steak ala Hotel Bintang 5 di Bali
                          5. Agar menambah aroma, kamu bisa goreng bawang merah bawang putih yang sudah diiris tipis, goreng hingga kecokelatan.  Remas-remas dan taburkan ke dalam kaldu dan tambahkan gula pasir. Jangan lupa untuk merasakan sop buntut dan menambah bumbu sesuai seleramu jika perlu.
                          6. Jika sudah hidangkan sop buntut dengan irisan tomat, kentang , wortel dan daun bawang. Nikmati sop buntut selagi hangat.                                      
                          """);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        textBahan.setText("""
                          Bahannya :
                          500 gram daging sapi yang dipotong-potong persegi
                          20 gram cabai rawit
                          6 buah bawang merah
                          3 siung bawang putih
                          3 butir kemiri 
                          4 gelas santan kental
                          2 ruas lengkuas yang dimemarkan
                          2 sendok teh garam
                          1 sendok teh asam kandis
                          1 lembar daun kunyit
                          1 lembar daun jeruk
                          1 batang serai yang dimemarkan
                          1 ruas jari jahe
                          1/2 sendok teh bubuk kunyit
                          
                          Cara membuatnya : 
                          1. Haluskan cabai rawit, bawang putih, merah, bubuk kunyit, kemiri, dan jahe secara bersamaan.
                          2. Tambahkan daging, santan, bumbu halus, asam kandis, serai, daun jeruk, dan kunyit ke dalam panci yang sudah berisi air mendidih. Aduk hingga merata.
                          3. Nyalakan api, masak api sedang dan harus diaduk terus. Ketika sudah mendidih, tambahkan garam, lalu aduk lagi tanpa berhenti.
                          4. Masak rendang hingga santannya meresap ke daging. Dengan begitu, daging akan lembut.
                          
                          """);
    }//GEN-LAST:event_button6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textBahan;
    // End of variables declaration//GEN-END:variables
}
